name: mps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py310hc377ac9_7
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.12.12=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2023.11.17=py310hca03da5_0
  - cffi=1.15.1=py310h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py310h48ca7d4_0
  - cryptography=41.0.7=py310h4c55245_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py310h0f1eb42_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - eigen=3.4.0=h48ca7d4_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h313beb8_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.9.0=py310hca03da5_0
  - fontconfig=2.14.1=hee714a5_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - glib=2.69.1=h514c7bf_2
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py310h8c48613_0
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h05c076b_3
  - icu=68.1=hc377ac9_0
  - idna=3.4=py310hca03da5_0
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib_metadata=7.0.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyh3cd1d5f_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py310hca03da5_0
  - joblib=1.2.0=py310hca03da5_0
  - jpeg=9e=h80987f9_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.1=py310hbe9552e_0
  - kiwisolver=1.4.4=py310h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.4.0=h3e2b118_1
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.15=h02f6b3c_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.10.0=h02f6b3c_2
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.1=py310h1a28f6b_0
  - matplotlib=3.8.0=py310hca03da5_0
  - matplotlib-base=3.8.0=py310h46d7db6_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py310hca03da5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=ha71a6ea_2
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.1=py310hca03da5_0
  - numpy=1.26.0=py310h3b2db8e_0
  - numpy-base=1.26.0=py310ha9811e2_0
  - opencv=4.6.0=py310hc90a7da_5
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.2.0=h0d3ecfb_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=hc377ac9_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py310h3b245a6_0
  - pip=23.3=py310hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py310hd125d64_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py310hca03da5_0
  - pyparsing=3.0.9=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.13=h2469fbe_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.1.1=py3.10_0
  - pyyaml=6.0.1=py310h80987f9_0
  - pyzmq=25.0.2=py310hc407298_0
  - qt-main=5.15.2=h9b4df51_9
  - qt-webengine=5.15.9=h2903aaf_7
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py310hca03da5_0
  - scikit-learn=1.3.0=py310h46d7db6_0
  - scipy=1.11.4=py310h20cbe94_0
  - setuptools=68.0.0=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py310hca03da5_0
  - terminaltables=3.1.10=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=h5083fa2_1
  - torchvision=0.16.1=py310_cpu
  - tornado=6.3.3=py310h2aa6e3c_1
  - tqdm=4.65.0=py310h33ce5c2_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py310hca03da5_0
  - urllib3=1.26.18=py310hca03da5_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.41.2=py310hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=hd90d995_0
  - pip:
      - fastargs==1.2.0
      - pandas==2.1.4
      - pytz==2023.3.post1
      - tzdata==2023.3
prefix: /Users/janulm/miniconda3/envs/mps
